x-base:
  &base
  platform: linux/x86_64
  build:
    context: .
  volumes:
    - .:/app/
    - /app/node_modules
    - /app/packages/nextjs/node_modules
    - /app/packages/foundry/node_modules
    - /app/packages/foundry/lib


services:
  yarn-chain:
    <<: *base
    command:
      - yarn
      - chain
      - --host
      - 0.0.0.0
    ports:
      - "8545:8545"

  yarn-start:
    <<: *base
    tty: true
    stdin_open: true
    command:
      - yarn
      - start
      - --hostname
      - 0.0.0.0
    ports:
      - "3000:3000"
